// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { config } from "dotenv";
import path from "path";

// Load .env then .env.local so .env.local overrides (Next.js convention). Prisma CLI then sees DATABASE_URL.
config({ path: path.resolve(process.cwd(), ".env") });
config({ path: path.resolve(process.cwd(), ".env.local") });

import { defineConfig } from "prisma/config";

// Supabase pooler needs pgbouncer=true for Prisma CLI (migrate, db push)
function getDatasourceUrl(): string | undefined {
  const url = process.env["DATABASE_URL"];
  if (!url) return url;
  if (
    (url.includes("supabase") && url.includes("6543")) ||
    url.includes("pooler.supabase")
  ) {
    if (!url.includes("pgbouncer=true")) {
      return url.includes("?") ? `${url}&pgbouncer=true` : `${url}?pgbouncer=true`;
    }
  }
  return url;
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: getDatasourceUrl(),
  },
});
